specfile_path: hexchat.spec
actions:
  get-current-version:
    - 'pwd'
    - 'cat .git/HEAD'
    - 'sed -nE ''s/^Version: +(.+)$/\1/p'' hexchat.spec'
jobs:
  - job: copr_build
    trigger: commit
    metadata:
      branch: fedora
      targets:
        - fedora-all
      owner: csomh
      project: hexchat
