specfile_path: hexchat.spec
actions:
  get-current-version: "make test"
# current_version_command: ["make", "test"]
jobs:
  - job: copr_build
    trigger: commit
    metadata:
      branch: fedora
      targets:
        - fedora-all
      owner: csomh
      project: hexchat
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
      - fedora-stable
